<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.206" timestamp="2024-07-03T15:56:18.514707" hostname="DESKTOP-F7B0BRF"><testcase classname="pytest" name="internal" time="0.000"><error message="internal error">Traceback (most recent call last):
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\main.py", line 285, in wrap_session
    session.exitstatus = doit(config, session) or 0
                         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\main.py", line 339, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\pluggy\_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\logging.py", line 807, in pytest_runtestloop
    return (yield)  # Run all the tests.
            ^^^^^
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\main.py", line 364, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\pluggy\_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\warnings.py", line 111, in pytest_runtest_protocol
    return (yield)
            ^^^^^
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\assertion\__init__.py", line 176, in pytest_runtest_protocol
    return (yield)
            ^^^^^
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\unittest.py", line 422, in pytest_runtest_protocol
    res = yield
          ^^^^^
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\faulthandler.py", line 85, in pytest_runtest_protocol
    return (yield)
            ^^^^^
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\runner.py", line 116, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\runner.py", line 129, in runtestprotocol
    rep = call_and_report(item, "setup", log)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\runner.py", line 243, in call_and_report
    report: TestReport = ihook.pytest_runtest_makereport(item=item, call=call)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dipanjana Saha\AppData\Local\Programs\Python\Python312\Lib\site-packages\pluggy\_callers.py", line 156, in _multicall
    teardown[0].send(outcome)
  File "C:\Users\Dipanjana Saha\PycharmProjects\PythonSelFramework\tests\conftest.py", line 50, in pytest_runtest_makereport
    _capture_screenshot(file_name)
  File "C:\Users\Dipanjana Saha\PycharmProjects\PythonSelFramework\tests\conftest.py", line 58, in _capture_screenshot
    driver.get_screenshot_as_file(name)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_screenshot_as_file'</error></testcase></testsuite></testsuites>